name: Fetch Weather Data

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5:00 UTC (~7:00 Berlin time)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run weather script
      run: python fetch_weather.py

    - name: Commit and push CSV if changed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add berlin_pankow_franzbucholz_weather_forecast.csv
        git diff --quiet && echo "No changes to commit" || git commit -m "Update weather data"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/THDOOO/weather-forecast-automation.git
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


